import StyleDictionary from 'style-dictionary';

const ROOT_VAR_PREFIX = 'omni';

/* Strip the leading "color" / theme prefix from a token path so the
 * emitted CSS-var name reads cleanly. Examples:
 *   color.primitive.neutral.light0     -> primitive-neutral-light0
 *   color.theme.light.text.body        -> text-body              (theme-stripped)
 *   color.theme.dark.text.body         -> text-body              (theme-stripped)
 *   font.family.sans                   -> font-family-sans
 *   space.4                            -> space-4
 *   shadow.elevation-2                 -> shadow-elevation-2     */
const varName = (token, { stripTheme = false } = {}) => {
  const segs = [...token.path];
  if (segs[0] === 'color') {
    segs.shift();
    if (stripTheme && segs[0] === 'theme') {
      segs.shift();
      segs.shift();
    }
  }
  return `--${ROOT_VAR_PREFIX}-${segs.join('-')}`;
};

const valOf = (t) => t.$value ?? t.value;

StyleDictionary.registerFormat({
  name: 'css/themes',
  format: async ({ dictionary }) => {
    const all = dictionary.allTokens.filter(t => !t.path.some(p => p === '_meta'));
    const primitives  = all.filter(t => t.path[0] === 'color' && t.path[1] === 'primitive');
    const lightTheme  = all.filter(t => t.path[0] === 'color' && t.path[1] === 'theme' && t.path[2] === 'light');
    const darkTheme   = all.filter(t => t.path[0] === 'color' && t.path[1] === 'theme' && t.path[2] === 'dark');
    const nonColor    = all.filter(t => t.path[0] !== 'color');

    const line = (token, opts) => `  ${varName(token, opts)}: ${valOf(token)};`;

    return [
      '/* Auto-generated by Style Dictionary. Do not edit. */',
      ':root {',
      '  /* — colors: primitive palette — */',
      ...primitives.map(t => line(t)),
      '',
      '  /* — colors: light theme (omni-classic) — */',
      ...lightTheme.map(t => line(t, { stripTheme: true })),
      '',
      '  /* — typography, spacing, radii, borders, shadows, motion, z-index — */',
      ...nonColor.map(t => line(t)),
      '}',
      '',
      '[data-theme="dark"] {',
      '  /* — colors: dark theme (oai) — */',
      ...darkTheme.map(t => line(t, { stripTheme: true })),
      '}',
      ''
    ].join('\n');
  }
});

export default {
  source: ['tokens/tokens.json'],
  platforms: {
    css:  { transformGroup: 'css', buildPath: 'dist/', files: [{ destination: 'tokens.css',  format: 'css/themes' }] },
    json: { transformGroup: 'js',  buildPath: 'dist/', files: [{ destination: 'tokens.json', format: 'json' }] },
    js:   { transformGroup: 'js',  buildPath: 'dist/', files: [{ destination: 'tokens.js',   format: 'javascript/es6' }] }
  }
};
