#!/usr/bin/env python3
"""Regenerate index.html, the per-email download zips, the demo wrappers,
and the grid thumbnails from the repo.

Run this after changing any email template, then commit the result:

    python3 build-index.py && git add -A && git commit

"Last updated" comes from each file's most recent git commit, so it stays
truthful on its own. Hand-editing the dates in index.html would rot the
moment a template changed.

Thumbnails are rendered from the real templates with Playwright, so a
preview can never drift from the email it depicts. If Playwright is not
available the script keeps any thumbnails already on disk and warns,
rather than failing the whole build.
"""
import html
import os
import re
import subprocess
import sys
import zipfile
from datetime import datetime

# Playwright and Pillow live in the user site-packages on this machine.
sys.path.insert(0, os.path.expanduser("~/Library/Python/3.9/lib/python/site-packages"))

ROOT = os.path.dirname(os.path.abspath(__file__))
DOWNLOADS = os.path.join(ROOT, "downloads")
VIEW = os.path.join(ROOT, "view")
THUMBS = os.path.join(ROOT, "thumbs")

# The live host the templates hotlink their images from. When rendering a
# thumbnail we serve those bytes off the local checkout instead, so a preview
# reflects the working tree (and builds without network).
LIVE_HOST = "https://oai-one.vercel.app/"

# Thumbnail geometry. Captured at the email's real 600px card width plus
# gutters, then cover-cropped from the TOP -- the masthead/headline/graphic
# is what identifies an email; its footer is identical across all of them.
THUMB_VIEWPORT = (680, 660)
THUMB_OUT = (900, 675)  # 4:3, retina-ish for a ~300-450px grid cell

# The two GAZETTE designs share a headline with each other, so each record's
# variant label is what actually distinguishes the cards.
#
# Anything whose variant starts with "Template" is grouped into its own row at
# the top of the page (see SECTIONS below).
#
# The two MATRIX designs were removed from the roster: their demo pages were
# deleted on request, and since this script regenerates view/ on every run,
# un-registering them here is what makes that stick. Their source files stay in
# the repo -- they are the original deliverables from the matrix package and are
# still referenced by README.txt -- they are simply no longer published to the
# index, previewed, thumbnailed or zipped.
EMAILS = [
    ("gazette-with-image.html", "Template 01", "Gazette — with brand graphic"),
    ("gazette-no-image.html", "Template 02", "Gazette — type-only, nothing to block"),
    ("storyboard.html", "Storyboard", "Skill spotlight — built on Template 01"),
    ("workflows.html", "Introducing Workflows", "Workflow launch — built on Template 01"),
    ("weekly-digest.html", "Weekly Digest", "Corvache workspace week in review — built on Template 01"),
    ("recommended-skills.html", "Recommended Skills", "Skill suggestions — built on Template 02"),
    ("welcome.html", "Welcome", "New-user welcome — built on Template 01"),
    ("back-online.html", "Service notice · back online", "Maintenance complete — built on Template 01"),
    ("maintenance.html", "Service notice · going down", "Scheduled maintenance — built on Template 01"),
    ("shared-file.html", "Shared File", "Share notification with a file tile"),
    ("centered-with-gif.html", "Announcement · centred", "Uses the persona animation"),
]

# Demo wrapper. The email templates themselves stay untouched: they are the
# deliverable that gets zipped and pasted into an ESP, so a fixed-position
# button (or logo) living inside one would ship as part of the real email
# (and land in the download). The wrapper iframes the pristine file and owns
# ALL the site chrome -- the download button, and now the home logo too.
VIEW_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>__TITLE__ — preview</title>
<!-- GENERATED BY build-index.py — do not hand-edit; rerun the script instead. -->
<style>
  html,body{margin:0;padding:0}
  body{background:#f6f7fa}
  iframe{display:block;width:100%;height:100vh;border:0}
  /* height is corrected by JS on load -- see below -- to the email's
     real content height, so no part of it hides behind a nested scrollbar */
  .home, .dl{
    position:fixed; top:20px; z-index:10;
    display:inline-flex; align-items:center; gap:8px;
    padding:9px 14px; background:#ffffff; color:#1b1d21;
    border:1px solid #dddfe1; border-radius:2px; text-decoration:none;
    font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    font-size:12px; font-weight:600; letter-spacing:.01em;
    box-shadow:0 1px 3px rgba(19,21,23,.08);
  }
  .home{left:20px; font-weight:800; letter-spacing:-.01em; font-size:13px;}
  .dl{right:20px;}
  .home:hover, .dl:hover{color:#1858ee; border-color:#c3c9d4; box-shadow:0 2px 8px rgba(19,21,23,.12)}
  .home:focus-visible, .dl:focus-visible{outline:2px solid #1858ee; outline-offset:2px}
  .dl svg{flex:0 0 auto}
  @media (max-width:520px){
    .home, .dl{top:12px; padding:9px; gap:0}
    .home{left:12px} .dl{right:12px}
    .dl span{display:none}
  }
  @media print{ .home, .dl{display:none} }
</style>
</head>
<body>
  <a class="home" href="https://oai-one.vercel.app/" aria-label="Back to OAI - Email and Communications">OMNI &#10022;</a>
  <a class="dl" href="__ZIP__" download title="Download __FILE__ as a zip (__KB__ KB)" aria-label="Download __FILE__ as a zip">
    <svg viewBox="0 0 16 16" width="15" height="15" aria-hidden="true" focusable="false">
      <path d="M8 1.5v8m0 0 3.2-3.2M8 9.5 4.8 6.3" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M2.5 11.5v1.6a1.4 1.4 0 0 0 1.4 1.4h8.2a1.4 1.4 0 0 0 1.4-1.4v-1.6" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
    </svg>
    <span>Download</span>
  </a>
  <iframe src="__SRC__" title="__TITLE__ email preview"></iframe>
  <script>
    (function () {
      var f = document.querySelector('iframe');
      function fit() {
        try {
          var h = f.contentDocument.body.scrollHeight; // NOT documentElement --
          // that one is defined as "at least the viewport", so it silently
          // under-reports when content is shorter than the iframe box.
          if (h > 0) f.style.height = h + 'px';
        } catch (e) {}
      }
      f.addEventListener('load', function () {
        fit();
        setTimeout(fit, 300); // late-loading images can still grow the height
      });
    })();
  </script>
__EXTRA__
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Content rendered BELOW the email frame on a demo page (never inside the
# email itself -- these pages are the showcase, the email stays the
# deliverable). Keyed by email filename.
#
# The shared-file hero variants: the same hero component -- Canvas cover
# field behind a centred white file card -- swapped across five of the six
# Canvas cover treatments. 03 BUBBLE is omitted because that is the cover
# the live email already uses.
_HERO_VARIANTS = [
    ("01 Rays",  "tile-01-rays-bg.png",  "#e8eefd", "wd-gw-canvas-review.png",
     "Q4 Brand Refresh &mdash; Working Canvas", "Modified Feb 14, 2026 &nbsp;&middot;&nbsp; DDB Worldwide"),
    ("02 Tick",  "tile-02-tick-bg.png",  "#e8eefd", "wd-gw-workflow-social.png",
     "Launch Social Refresh", "Modified Feb 13, 2026 &nbsp;&middot;&nbsp; TBWA"),
    ("04 Burst", "tile-04-burst-bg.png", "#e8eefd", "wd-gw-text-shoppers.png",
     "SE Region EV Shoppers", "Modified Feb 3, 2026 &nbsp;&middot;&nbsp; Annalect"),
    ("05 Field", "tile-05-field-bg.png", "#e8eefd", "wd-gw-video-buyers.png",
     "New Car buyers 2025", "Modified Feb 3, 2026 &nbsp;&middot;&nbsp; Critical Mass"),
    ("06 Grid",  "tile-06-grid-bg.png",  "#e8eefd", "wd-gw-workflow-hero.png",
     "Hero Image Pipeline", "Modified Feb 13, 2026 &nbsp;&middot;&nbsp; BBDO Worldwide"),
]

def _hero_variant(label, bg, fill, icon, name, meta):
    # relative: the demo page is served from the same origin as /assets,
    # so this works locally AND deployed, with no dependency on the live
    # host being reachable (the email itself still needs absolute URLs --
    # mail clients have no origin to resolve against).
    H = "../assets/"
    SANS = "'Helvetica Neue',Helvetica,Arial,sans-serif"
    return f"""      <figure class="hv">
        <figcaption class="hv-cap">{label}</figcaption>
        <div class="hv-tile" style="background-color:{fill};background-image:url('{H}{bg}');">
          <div class="hv-card">
            <img src="{H}{icon}" width="40" height="40" alt="">
            <div class="hv-text">
              <div class="hv-name">{name}</div>
              <div class="hv-meta">{meta}</div>
            </div>
          </div>
        </div>
      </figure>"""

SHARED_FILE_EXTRA = """
<section class="variants">
  <div class="variants-inner">
    <h2>Hero component &mdash; Canvas cover variants</h2>
    <p class="variants-sub">The same hero, across five Canvas cover treatments. The live email above uses 03 Bubble.</p>
    <div class="hv-grid">
""" + "\n".join(_hero_variant(*v) for v in _HERO_VARIANTS) + """
    </div>
  </div>
</section>
<style>
  .variants{background:#ffffff;border-top:1px solid #dddfe1;padding:24px 24px 88px}
  .variants-inner{max-width:1120px;margin:0 auto}
  .variants h2{margin:0 0 6px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    font-size:19px;font-weight:700;letter-spacing:-0.01em;color:#1b1d21}
  .variants-sub{margin:0 0 30px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    font-size:13px;line-height:1.5;color:#6b6d7a}
  .hv-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(400px,1fr));gap:26px}
  .hv{margin:0}
  .hv-cap{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:10px;font-weight:600;
    text-transform:uppercase;letter-spacing:0.16em;color:#9b9dac;padding:0 0 9px 1px}
  /* same proportions as the email hero: 486x414 */
  .hv-tile{aspect-ratio:486/414;border:1px solid #dddfe1;background-size:cover;
    background-position:center;display:flex;align-items:center;justify-content:center;padding:20px}
  .hv-card{box-sizing:border-box;display:flex;align-items:center;gap:14px;background:#ffffff;border:1px solid #dddfe1;
    border-radius:6px;padding:18px 20px;width:340px;max-width:100%}
  .hv-card img{display:block;width:40px;height:40px;flex:0 0 auto}
  .hv-name{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:15px;font-weight:600;
    letter-spacing:-0.01em;line-height:1.35;color:#1b1d21}
  .hv-meta{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:11.5px;
    line-height:1.5;color:#6b6d7a;padding-top:3px}
  @media (max-width:640px){ .variants{padding:20px 16px 64px} .hv-grid{gap:18px} }
</style>
"""

VIEW_EXTRAS = {"shared-file.html": SHARED_FILE_EXTRA}


def git_last_modified(path):
    iso = subprocess.run(
        ["git", "log", "-1", "--format=%cI", "--", path],
        cwd=ROOT, capture_output=True, text=True,
    ).stdout.strip()
    if not iso:  # not yet committed -- fall back to mtime
        return datetime.fromtimestamp(os.path.getmtime(os.path.join(ROOT, path))).astimezone()
    return datetime.fromisoformat(iso)


def headline(path):
    src = open(os.path.join(ROOT, path), encoding="utf-8").read()
    m = re.search(r"<h1[^>]*>(.*?)</h1>", src, re.S)
    if not m:
        return path
    raw = re.sub(r"<br\s*/?>", " ", m.group(1), flags=re.I)  # line breaks -> word boundary
    text = html.unescape(re.sub(r"<[^>]+>", "", raw))
    text = " ".join(text.split()).rstrip(".")
    # drop leading personalisation, e.g. "Andrew, your Q3 ..." -> "Q3 ..."
    text = re.sub(r"^[A-Z][a-z]+,\s+your\s+", "", text)
    return text


def build_zip(path):
    os.makedirs(DOWNLOADS, exist_ok=True)
    name = os.path.splitext(path)[0] + ".zip"
    out = os.path.join(DOWNLOADS, name)
    # deterministic: fixed timestamp so rebuilds don't churn git
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        info = zipfile.ZipInfo(path, date_time=(2026, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = 0o644 << 16
        z.writestr(info, open(os.path.join(ROOT, path), "rb").read())
    return name, os.path.getsize(out)


def build_view(path, title, zip_name, kb, extra=""):
    os.makedirs(VIEW, exist_ok=True)
    out_name = os.path.basename(path)
    doc = (VIEW_TEMPLATE
           .replace("__TITLE__", html.escape(title))
           .replace("__FILE__", html.escape(path))
           .replace("__ZIP__", "../downloads/" + zip_name)
           .replace("__KB__", str(kb))
           .replace("__SRC__", "../" + path)
           .replace("__EXTRA__", extra))
    open(os.path.join(VIEW, out_name), "w", encoding="utf-8").write(doc)
    return "view/" + out_name


MIME = {".png": "image/png", ".gif": "image/gif", ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg", ".svg": "image/svg+xml"}


def build_thumbs(records):
    """Screenshot each template into thumbs/<name>.png."""
    try:
        from playwright.sync_api import sync_playwright
        from PIL import Image
    except ImportError as exc:
        print(f"  ! thumbnails skipped ({exc}); keeping any already on disk")
        return
    os.makedirs(THUMBS, exist_ok=True)
    vw, vh = THUMB_VIEWPORT
    tw, th = THUMB_OUT

    def serve_local(route, request):
        """Fulfil the templates' live-host image URLs from this checkout."""
        rel = request.url[len(LIVE_HOST):].split("?")[0]
        local = os.path.join(ROOT, rel)
        if os.path.isfile(local):
            ext = os.path.splitext(local)[1].lower()
            route.fulfill(status=200, body=open(local, "rb").read(),
                          headers={"content-type": MIME.get(ext, "application/octet-stream")})
        else:
            route.abort()

    with sync_playwright() as p:
        browser = p.chromium.launch()
        ctx = browser.new_context(viewport={"width": vw, "height": vh},
                                  device_scale_factor=2)
        ctx.route(LIVE_HOST + "**", serve_local)
        page = ctx.new_page()
        for r in records:
            page.goto("file://" + os.path.join(ROOT, r["file"]), wait_until="load")
            page.wait_for_timeout(700)
            shot = os.path.join(THUMBS, r["thumb_name"])
            page.screenshot(path=shot)  # viewport-only: the top of the email
            im = Image.open(shot).convert("RGB")
            # cover-crop from the top, then quantise (these are flat, few-colour
            # renders -- 128 colours is visually lossless here and much smaller)
            scale = max(tw / im.width, th / im.height)
            im = im.resize((round(im.width * scale), round(im.height * scale)), Image.LANCZOS)
            im = im.crop(((im.width - tw) // 2, 0, (im.width - tw) // 2 + tw, th))
            im.quantize(colors=128, method=Image.MAXCOVERAGE).save(shot, optimize=True)
            r["thumb_kb"] = round(os.path.getsize(shot) / 1024)
        browser.close()


records = []
for path, variant, blurb in EMAILS:
    dt = git_last_modified(path)
    zip_name, zip_size = build_zip(path)
    title = headline(path)
    kb = round(zip_size / 1024)
    thumb_name = os.path.splitext(path)[0] + ".png"
    records.append({
        "file": path,
        "view": build_view(path, title, zip_name, kb, VIEW_EXTRAS.get(path, "")),
        "thumb_name": thumb_name,
        "thumb": "thumbs/" + thumb_name,
        "title": title,
        "variant": variant,
        "blurb": blurb,
        "iso": dt.isoformat(),
        "date": dt.strftime("%-d %b %Y"),
        "sort": dt.timestamp(),
        "zip": "downloads/" + zip_name,
        "kb": kb,
        "thumb_kb": 0,
    })

# most recent first; stable tie-break so equal timestamps keep a fixed order
records.sort(key=lambda r: (-r["sort"], r["file"]))
build_thumbs(records)

DL_SVG = ('<svg viewBox="0 0 16 16" width="15" height="15" aria-hidden="true" focusable="false">'
          '<path d="M8 1.5v8m0 0 3.2-3.2M8 9.5 4.8 6.3" fill="none" stroke="currentColor" '
          'stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>'
          '<path d="M2.5 11.5v1.6a1.4 1.4 0 0 0 1.4 1.4h8.2a1.4 1.4 0 0 0 1.4-1.4v-1.6" '
          'fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg>')

def card_html(r):
    haystack = html.escape(
        (r["title"] + " " + r["variant"] + " " + r["blurb"] + " " +
         r["file"] + " " + r["date"]).lower(), quote=True)
    return f'''        <li class="card" data-search="{haystack}">
          <a class="shot" href="{r['view']}" tabindex="-1" aria-hidden="true">
            <img src="{r['thumb']}" width="900" height="675" alt="" loading="lazy" decoding="async">
          </a>
          <div class="meta">
            <a class="open" href="{r['view']}">
              <span class="t">{html.escape(r['title'])}</span>
              <span class="v">{r['variant']}</span>
            </a>
            <div class="foot">
              <time class="d" datetime="{r['iso']}">{r['date']}</time>
              <a class="dl" href="{r['zip']}" download title="Download {html.escape(r['file'])} as a zip ({r['kb']} KB)" aria-label="Download {html.escape(r['file'])} as a zip">{DL_SVG}</a>
            </div>
          </div>
        </li>'''


# Templates get their OWN grid, not just a sort order -- a shared grid would let
# them share a row with the emails below at some viewport widths. Two grids
# guarantees the break at every width.
templates = [r for r in records if r["variant"].startswith("Template")]
others = [r for r in records if not r["variant"].startswith("Template")]
# Templates read in label order (01, 02), not by date. They were committed
# together, so the date sort's filename tie-break otherwise put 02 first.
templates.sort(key=lambda r: r["variant"])

SECTIONS = [("Templates", templates), ("Emails", others)]
sections_html = []
for label, group in SECTIONS:
    if not group:
        continue
    sections_html.append(
        f'''    <section class="section" data-section="{label.lower()}">
      <h2 class="section-label">{label}</h2>
      <ul class="grid">
{chr(10).join(card_html(r) for r in group)}
      </ul>
    </section>''')

doc = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>OAI — Email and Communications</title>
<!-- GENERATED BY build-index.py — do not hand-edit; rerun the script instead. -->
<style>
  :root{{
    --ink:#1b1d21; --muted:#6b6d7a; --faint:#9b9dac;
    --line:#dddfe1; --blue:#1858ee; --bg:#f6f7fa; --card:#ffffff;
  }}
  *{{box-sizing:border-box}}
  body{{
    margin:0; background:var(--bg); color:var(--ink);
    font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
    -webkit-font-smoothing:antialiased;
  }}
  .wrap{{max-width:1440px; margin:0 auto; padding:28px 32px 96px}}

  /* Header is one row: logo (home link) | micro-label (the page's real h1,
     just styled small -- "micrographic", per spec) | search toggle. Replacing
     the old four stacked, centered blocks (logo/h1/search bar/count) with a
     single row is most of "shorten the vertical header space" by itself. */
  .topbar{{
    /* left/right size to their own content (logo, icon); the centre track is
       minmax(0,1fr) rather than auto so it can actually shrink below the
       label's natural width -- an auto track can't, and the label would
       overflow the viewport at narrow widths instead of truncating. */
    display:grid; grid-template-columns:auto minmax(0,1fr) auto; align-items:center;
    gap:16px; margin:0 0 4px;
  }}
  .logo{{
    font-weight:800; letter-spacing:-.01em; font-size:17px;
    color:var(--ink); text-decoration:none; white-space:nowrap;
  }}
  .logo:hover{{color:var(--blue)}}
  .logo:focus-visible{{outline:2px solid var(--blue); outline-offset:2px}}
  h1.micro-label{{
    margin:0; min-width:0; font-size:10.5px; font-weight:600;
    text-transform:uppercase; letter-spacing:.16em; color:var(--faint);
    white-space:nowrap; overflow:hidden; text-overflow:ellipsis; text-align:center;
  }}
  /* Third topbar cell: the sibling-catalog swap link plus the search icon,
     grouped so the swap link doesn't need its own grid column (which would
     unbalance the centered micro-label against the single-item left column). */
  .topbar-actions{{ justify-self:end; display:flex; align-items:center; gap:16px; }}
  .nav-swap{{
    font-size:11px; font-weight:600; text-transform:uppercase; letter-spacing:.1em;
    color:var(--muted); text-decoration:none; white-space:nowrap;
  }}
  .nav-swap:hover{{color:var(--blue)}}
  .nav-swap:focus-visible{{outline:2px solid var(--blue); outline-offset:2px}}
  .search-toggle{{
    display:inline-flex; align-items:center; justify-content:center;
    width:34px; height:34px; padding:0; border:1px solid transparent; border-radius:2px;
    background:none; color:var(--muted); cursor:pointer;
  }}
  .search-toggle:hover, .search-toggle[aria-expanded="true"]{{
    color:var(--blue); border-color:var(--line); background:var(--card);
  }}
  .search-toggle:focus-visible{{outline:2px solid var(--blue); outline-offset:2px}}

  /* Collapsed by default (zero height); the icon toggles .open. visibility
     switches instantly (so a collapsed input can't eat a Tab stop) while
     max-height/opacity/margin animate -- visibility itself is not part of
     that transition, so the two don't fight. */
  .search-row{{
    visibility:hidden; max-height:0; opacity:0; overflow:hidden;
    transition:max-height .22s ease, opacity .18s ease, margin .22s ease;
  }}
  .search-row.open{{visibility:visible; max-height:140px; opacity:1; margin:18px 0 26px}}

  .search{{position:relative; max-width:520px; margin:0 auto 10px}}
  .search > svg{{position:absolute; left:14px; top:50%; transform:translateY(-50%); color:var(--faint); pointer-events:none}}
  #q{{
    width:100%; padding:13px 40px; font:inherit; font-size:14px; color:var(--ink);
    background:var(--card); border:1px solid var(--line); border-radius:2px; outline:none;
  }}
  #q::placeholder{{color:var(--faint)}}
  #q:focus{{border-color:var(--blue); box-shadow:0 0 0 3px rgba(24,88,238,.12)}}
  #clear{{
    position:absolute; right:8px; top:50%; transform:translateY(-50%); display:none;
    border:0; background:none; cursor:pointer; color:var(--faint); font-size:18px;
    line-height:1; padding:6px 8px;
  }}
  #clear:hover{{color:var(--ink)}}
  .count{{font-size:11px; color:var(--faint); text-align:center; margin:0; min-height:14px}}

  /* full-width grid: cells size themselves, so the row count follows the
     viewport instead of a fixed column count */
  .grid{{
    list-style:none; margin:0; padding:0;
    display:grid; grid-template-columns:repeat(auto-fill, minmax(300px, 1fr)); gap:22px;
  }}
  .section + .section{{margin-top:40px}}
  .section-label{{
    margin:0 0 14px; font-size:11px; font-weight:600; text-transform:uppercase;
    letter-spacing:.16em; color:var(--faint);
    padding-bottom:10px; border-bottom:1px solid var(--line);
  }}
  .section.hidden{{display:none}}
  .card{{
    background:var(--card); border:1px solid var(--line); display:flex; flex-direction:column;
    transition:border-color .15s ease, box-shadow .15s ease, transform .15s ease;
  }}
  .card:hover{{border-color:#c3c9d4; box-shadow:0 4px 16px rgba(19,21,23,.08); transform:translateY(-2px)}}

  /* the preview. Fixed 4:3 window, image anchored to the top so every card
     crops at the same place and the row reads as a set. */
  .shot{{display:block; aspect-ratio:4/3; overflow:hidden; background:var(--bg); border-bottom:1px solid var(--line)}}
  .shot img{{width:100%; height:100%; object-fit:cover; object-position:top center; display:block}}

  .meta{{padding:14px 16px 12px; display:flex; flex-direction:column; gap:10px; flex:1}}
  .open{{display:flex; flex-direction:column; gap:3px; text-decoration:none; color:inherit}}
  .t{{font-size:14px; font-weight:600; line-height:1.3}}
  .open:hover .t{{color:var(--blue)}}
  .v{{font-size:11.5px; color:var(--muted)}}
  .foot{{margin-top:auto; display:flex; align-items:center; justify-content:space-between; gap:10px;
        padding-top:10px; border-top:1px solid var(--line)}}
  .d{{font-size:11.5px; color:var(--faint); font-variant-numeric:tabular-nums}}
  .dl{{
    display:inline-flex; align-items:center; justify-content:center; width:30px; height:30px;
    color:var(--muted); border:1px solid transparent; border-radius:2px;
  }}
  .dl:hover{{color:var(--blue); border-color:var(--line); background:var(--bg)}}
  .dl:focus-visible, .open:focus-visible, #q:focus-visible{{outline:2px solid var(--blue); outline-offset:2px}}

  .empty{{display:none; padding:40px 18px; font-size:13px; color:var(--muted); text-align:center;
         background:var(--card); border:1px solid var(--line)}}
  .empty.on{{display:block}}
  footer{{text-align:center; font-size:11px; color:var(--faint); margin-top:44px}}

  @media (max-width:600px){{ .wrap{{padding:40px 18px 72px}} .grid{{gap:16px}} }}
</style>
</head>
<body>
  <div class="wrap">
    <header class="topbar">
      <a class="logo" href="https://oai-one.vercel.app/">OMNI &#10022;</a>
      <h1 class="micro-label">OAI - Email and Communications</h1>
      <div class="topbar-actions">
        <a class="nav-swap" href="site/index.html">Site Experience</a>
        <button id="searchToggle" class="search-toggle" type="button" aria-expanded="false" aria-controls="searchRow" aria-label="Search emails">
          <svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true" focusable="false">
            <circle cx="7" cy="7" r="4.6" fill="none" stroke="currentColor" stroke-width="1.4"/>
            <path d="M10.4 10.4 14 14" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
          </svg>
        </button>
      </div>
    </header>

    <div class="search-row" id="searchRow">
      <div class="search">
        <svg viewBox="0 0 16 16" width="15" height="15" aria-hidden="true" focusable="false">
          <circle cx="7" cy="7" r="4.6" fill="none" stroke="currentColor" stroke-width="1.4"/>
          <path d="M10.4 10.4 14 14" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
        </svg>
        <input id="q" type="search" autocomplete="off" placeholder="Search emails…" aria-label="Search emails" aria-controls="results">
        <button id="clear" type="button" aria-label="Clear search">&times;</button>
      </div>
      <p class="count" id="count" role="status" aria-live="polite"></p>
    </div>

    <div id="results">
{chr(10).join(sections_html)}
      <p class="empty" id="empty">No emails match that search.</p>
    </div>

    <footer>&copy; 2026 Omnicom Group Inc.</footer>
  </div>

<script>
(function () {{
  var toggle = document.getElementById('searchToggle'),
      row = document.getElementById('searchRow'),
      q = document.getElementById('q'),
      clear = document.getElementById('clear'),
      count = document.getElementById('count'),
      empty = document.getElementById('empty'),
      cards = [].slice.call(document.querySelectorAll('.card')),
      sections = [].slice.call(document.querySelectorAll('.section')),
      total = cards.length;

  function label(n) {{
    return n === total
      ? total + (total === 1 ? ' email' : ' emails')
      : n + ' of ' + total + ' emails';
  }}

  function filter() {{
    var term = q.value.trim().toLowerCase(), shown = 0;
    // every term must match, so "gazette image" narrows rather than widens
    var parts = term ? term.split(/\\s+/) : [];
    cards.forEach(function (card) {{
      var hay = card.getAttribute('data-search');
      var hit = parts.every(function (p) {{ return hay.indexOf(p) !== -1; }});
      card.style.display = hit ? '' : 'none';
      if (hit) shown++;
    }});
    // a section whose cards all filtered out hides its heading too, otherwise
    // a search leaves a labelled empty band behind
    sections.forEach(function (sec) {{
      var any = [].slice.call(sec.querySelectorAll('.card'))
        .some(function (c) {{ return c.style.display !== 'none'; }});
      sec.classList.toggle('hidden', !any);
    }});
    empty.classList.toggle('on', shown === 0);
    count.textContent = label(shown);
    clear.style.display = term ? 'block' : 'none';
  }}

  // Collapsed search: the icon reveals .search-row (see CSS); collapsing
  // it also clears any active term, since hiding the input while a filter
  // stayed applied would leave a shortened list with no visible reason why.
  function openSearch() {{
    toggle.setAttribute('aria-expanded', 'true');
    row.classList.add('open');
    q.focus();
  }}
  function closeSearch() {{
    toggle.setAttribute('aria-expanded', 'false');
    row.classList.remove('open');
    if (q.value) {{ q.value = ''; filter(); }}
  }}
  toggle.addEventListener('click', function (e) {{
    // stopPropagation so this same click doesn't also hit the
    // document-level "click outside" listener below and re-close
    // the row it just opened.
    e.stopPropagation();
    toggle.getAttribute('aria-expanded') === 'true' ? closeSearch() : openSearch();
  }});
  document.addEventListener('click', function (e) {{
    if (toggle.getAttribute('aria-expanded') === 'true' && !row.contains(e.target)) closeSearch();
  }});

  q.addEventListener('input', filter);
  q.addEventListener('keydown', function (e) {{
    if (e.key !== 'Escape') return;
    // first Escape clears a live term; only an Escape on an already-empty
    // field collapses the row, so clearing and dismissing stay two steps
    if (q.value) {{ q.value = ''; filter(); }}
    else {{ closeSearch(); toggle.focus(); }}
  }});
  clear.addEventListener('click', function () {{ q.value = ''; filter(); q.focus(); }});
  filter();
}})();
</script>
</body>
</html>
'''

open(os.path.join(ROOT, "index.html"), "w", encoding="utf-8").write(doc)
print(f"index.html written with {len(records)} records (newest first):")
for r in records:
    print(f"  {r['date']:>12}  {r['title'][:42]:<44} {r['variant']:<24} "
          f"zip {r['kb']}KB  thumb {r['thumb_kb']}KB")
